### ISSUE TITLE
multiplayer.html stops at "connecting to server..."

### ISSUE THREAD

**Issue by Bayside308** [Overv/WebCraft#18]
Hello!

I'm using a Windows 10 computer to test this out locally. I'm using the npm http-server as my web server, which is functioning properly. I'm opening the page through `localhost:8081/multiplayer.html`, and it allows me to enter a name. After that, however, it just freezes at "connecting to server...".

I'm able to start the server.js file with no issues.

The web server outputs this error:
`"POST /socket.io/?EIO=3&transport=polling&t=L-PW7s9" Error (404): "Not found"`
Chrome outputs this error:
`POST http://localhost:8081/socket.io/?EIO=3&transport=polling&t=L-PVxHX 405 (Method Not Allowed)`

**Comment by Overv** [comment]
Perhaps raise this issue with socket.io.

**Comment by Bayside308** [comment]
Will do! Is there anything else I should be doing that I missed? I am supposed to run a web server, as the server.js doesn't do that, right?

**Comment by Overv** [comment]
Ah, the problem is that it expects the WebSocket server to be on the same origin (`localhost:8081`) whereas I think the `server.js` hosts it on port 80. The HTML and WebSocket stuff should be served on the same port or you need to change the connecting code in `multiplayer.html`.

**Comment by Overv** [comment]
I just tested it on my own PC. I started the server with `node server.js` and browsed to `http://localhost:3000/multiplayer.html`. That works fine here.
