### ISSUE TITLE
How to make multiplayer online

### ISSUE THREAD

**Issue by ficopang** [Overv/WebCraft#21]
I want to make multiplayer online in heroku node js. I think the problem is the server.js not include listen ip.... I tried a lot of tutorial on youtube but it cant, anyone can help me?

**Comment by Overv** [comment]
The server.js listens on port 3000. Make sure to either change that to port 80 or use a reverse proxy.

See: https://github.com/Overv/WebCraft/blob/master/js/network.js#L268
