### ISSUE TITLE
Player's skin (Multiplayer)

### ISSUE THREAD

**Issue by ficopang** [Overv/WebCraft#24]
How to make custom skin for client nickname? (for example: someone using nickname aldi). so every one is steve skin, but aldi have his own skin

**Comment by Overv** [comment]
You would have to create an extra texture here:

https://github.com/Overv/WebCraft/blob/master/js/render.js#L91

And then bind that alternative texture instead of the default one here based on a nickname condition:

https://github.com/Overv/WebCraft/blob/master/js/render.js#L186
