### ISSUE TITLE
Black blocks / multiplayer.html not working

### ISSUE THREAD

**Issue by ZombieB1309** [Overv/WebCraft#42]
When I open multiplayer.html it's all black
It only works in certain ways

**Comment by AlotarioU** [comment]
Please tell me someone figured out how to fix this.

**Comment by ZombieB1309** [comment]
This is an issue with the server not being set up properly. You need to download node.js from https://nodejs.org/, install the dependencies using `npm install`, then run `node server.js` to run the server and connect on port 3000.
See #9

**Comment by Alotario** [comment]
We're running it on replit on our chromebooks because we're trying to make a little public server at our school. We don't know how to use node server.js via replit, do you have any idea how to do it that way? We have no idea what we're doing.

**Comment by ZombieB1309** [comment]
Your repl can't be run 24/7 on a starter plan so you'll probably need to keep the shell tab open on your device although the server can be run.

Here's a video I quickly prepared for quick repl.it setups. You will need to disable the 1 IP per user rule at 1:56.
https://cdn.discordapp.com/attachments/916487561600458753/930282813834526730/WebCraft_Setup_Video.mp4

**Comment by Alotario** [comment]
> Your repl can't be run 24/7 on a starter plan so you'll probably need to keep the shell tab open on your device although the server can be run.
> 
> Here's a video I quickly prepared for quick repl.it setups. You will need to disable the 1 IP per user rule at 1:56. https://cdn.discordapp.com/attachments/916487561600458753/930282813834526730/WebCraft_Setup_Video.mp4

this worked, thank you
this isnt a huge deal, but do you have any idea how he added the pointer lock?
