### ISSUE TITLE
mouse/pointer lock (navigator.pointer.lock)

### ISSUE THREAD

**Issue by pyrotechnick** [Overv/WebCraft#5]
http://dvcs.w3.org/hg/webevents/raw-file/default/mouse-lock.html
https://developer.mozilla.org/en/API/Mouse_Lock_API

**Comment by p3rlphr33k** [comment]
can someone elaborate on adding the pointer lock to webcraft? I have added the code so it locks in the pointer when the canvas is selected, the coordinates can be displayed in the console, but the movements do not register with the game and No errors. I used the example canvas loop function to call the mouse movefunction without luck..
